project_id = "hzkhillrqgssivrnufhg"

[functions.upload-file]
verify_jwt = true

[functions.get-conversations]
verify_jwt = true

[functions.save-chat]
verify_jwt = true

[functions.submit-query]
verify_jwt = true

[functions.manage-faqs]
verify_jwt = true