project_id = "hzkhillrqgssivrnufhg"

[functions.chat-completion]
verify_jwt = true

[functions.upload-file]
verify_jwt = true

[functions.get-conversations]
verify_jwt = true

[functions.save-chat]
verify_jwt = true