// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzkhillrqgssivrnufhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6a2hpbGxycWdzc2l2cm51ZmhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NTQxMjIsImV4cCI6MjA2ODEzMDEyMn0.YwGn4Ne8qB6XEO7N4f9GEm0wu6zlcAjpid9z-DfepeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});